package l14Exceptions;

import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;

public class Main {

	/*3 kinds of exception:
	 * 	1. checked exception
	 *  2. error exception
	 *  3. runtime exception*/
	
    private List<Integer> list;
    private static final int SIZE = 10;
    
    //List of numbers
    public Main () {
        list = new ArrayList<Integer>(SIZE);
        for (int i = 0; i < SIZE; i++) {
            list.add(new Integer(i));
        }
    }

    public void writeList() {
	// The FileWriter constructor throws IOException, which must be caught.
        PrintWriter out = new PrintWriter(new FileWriter("OutFile.txt"));

        for (int i = 0; i < SIZE; i++) {
            // The get(int) method throws IndexOutOfBoundsException, which must be caught.
            out.println("Value at: " + i + " = " + list.get(i));
        }
        out.close();
    }
	
	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
